name: Deploy Demo SPA/BFF

on:
  workflow_dispatch:
    inputs:
      env-profile:
        required: true
        type: choice
        options:
        - Staging
        - Release
        
permissions:
  contents: read    
  
jobs:
  stop_application:
    name: Stop III Site
    uses: baufestdemos/ci_dotnet/.github/workflows/stop_iis_site.yml@feature/pipeline
    with: 
      site-name: spabffdemo
      env-profile: ${{ inputs.env-profile }}
    secrets: inherit
        
  build_upload:
    name: Build & upload
    uses: baufestdemos/ci_dotnet/.github/workflows/build_and_upload.yml@feature/pipeline
    with: 
      env-profile: ${{ inputs.env-profile }}
    secrets: inherit
    
  deploy_spabff:
    needs: [stop_application, build_upload]
    uses: baufestdemos/ci_dotnet/.github/workflows/partial_spabff.yml@feature/pipeline
    with: 
      env-profile: ${{ inputs.env-profile }}
    secrets: inherit
        
  start_application:
    needs: [deploy_spabff]
    name: Start IIS Site
    uses: baufestdemos/ci_dotnet/.github/workflows/start_iis_site.yml@feature/pipeline
    with: 
      site-name: spabffdemo
      env-profile: ${{ inputs.env-profile }}
    secrets: inherit   
      

          
      
    
