name: Deploy Demo API

on:
  workflow_dispatch:
    inputs:
      env-profile:
        required: true
        type: choice
        options:
        - Staging
        - Release
        
      data-base:
        required: false
        type: boolean
        default: true
        
permissions:
  contents: read    
  
jobs:
  stop_application:
    name: Stop API Site
    uses: baufestdemos/ci_dotnet/.github/workflows/stop_iis_site.yml@feature/pipeline
    with: 
      service-name: apidemo
      env-profile: ${{ inputs.env-profile }}
    secrets: inherit
      
  build_upload:
    name: Build & upload
    uses: baufestdemos/ci_dotnet/.github/workflows/build_and_upload.yml@feature/pipeline
    with: 
      env-profile: ${{ inputs.env-profile }}
    secrets: inherit
    
  deploy_database:
    needs: [stop_application, build_upload]
    if: ${{ inputs.data-base }}
    name: Deploy Database
    uses: baufestdemos/ci_dotnet/.github/workflows/partial_database.yml@feature/pipeline
    with: 
      env-profile: ${{ inputs.env-profile }}
    secrets: inherit
    
  deploy_api:
    needs: [stop_application, build_upload]
    uses: baufestdemos/ci_dotnet/.github/workflows/partial_api.yml@feature/pipeline
    with: 
      env-profile: ${{ inputs.env-profile }}
    secrets: inherit
    
  start_application:
    needs: [deploy_database, deploy_api]
    name: Start API Site
    uses: baufestdemos/ci_dotnet/.github/workflows/start_iis_site.yml@feature/pipeline
    with: 
      service-name: apidemo
      env-profile: ${{ inputs.env-profile }}
    secrets: inherit
          
      
    
